#---
#apiVersion: extensions/v1beta1
#kind: Deployment
#metadata:
#  name: node-testing
#  labels:
#    app: api
#spec:
#  replicas: 2
#  template:
#  metadata:
#   labels:
#     app: Express
#  spec:
#    containers:
#     - name: testing-container
#       image: manasshk/testing-node-2
#       ports:
#         - containerPort: 8083
---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: node-testing
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: web-api
     spec:
       containers:
         - name: testing-node
           image: manasshk/testing-node-2
           ports:
             - containerPort: 8083